
  - name: Update APT package cache
    apt:
      update_cache: yes

  - name: Upgrade Nginx
    apt:
      name: nginx
      state: latest
    notify: Restart Nginx  # Notify the handler to restart Nginx

  # handlers:
  #   - name: Restart Nginx
  #     service:
  #       name: nginx
        # state: restarted
