- name: Update APT package cache
  apt:
    update_cache: yes
  become: yes

- name: Add Nginx repository
  apt_repository:
    repo: "deb http://nginx.org/packages/mainline/ubuntu focal nginx"
    state: present
    filename: nginx
  become: yes

- name: Install Nginx version 1.18.0
  apt:
    name: nginx=1.18.*
    state: present
  become: yes

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
  become: yes
